// copyright yarn spinner pty ltd
// licensed under the mit license

#pragma once

#include "CoreMinimal.h"
#include "Factories/Factory.h"
#include "YarnAssetFactory.generated.h"

/**
 * factory for importing .yarnproject files
 *
 * when a .yarnproject file is imported, this factory:
 * 1. calls ysc to compile the yarn scripts
 * 2. reads the generated .yarnc bytecode (no parsing - just raw bytes!)
 * 3. loads the string tables from csv
 * 4. creates a uyarnprogram asset
 *
 * this is much simpler than the old implementation because we don't need
 * to parse protobuf at import time - just copy the bytes and let nanopb
 * handle deserialization at runtime
 */
UCLASS()
class YARNSPINNEREDITOR_API UYarnAssetFactory : public UFactory
{
	GENERATED_BODY()

public:
	UYarnAssetFactory();

	// ufactory interface
	virtual UObject* FactoryCreateFile(UClass* InClass, UObject* InParent, FName InName, EObjectFlags Flags,
		const FString& Filename, const TCHAR* Parms, FFeedbackContext* Warn, bool& bOutOperationCanceled) override;

	virtual bool FactoryCanImport(const FString& Filename) override;

private:
	// compile a .yarnproject file using ysc
	// returns true if compilation succeeded
	bool CompileYarnProject(const FString& ProjectPath, const FString& OutputDir, const FString& OutputName, FString& OutError);

	// load string table from csv file generated by ysc
	void LoadStringTableFromCSV(class UYarnProgram* Program, const FString& CSVPath);

	// load metadata table from csv file
	void LoadMetadataFromCSV(class UYarnProgram* Program, const FString& CSVPath);

	// get path to ysc compiler binary
	FString GetYscPath() const;
};
